#!/bin/bash

cd build
echo $(./gen_workers.sh)
cd ..

CMD=make

for var in "$@"
do
	if [ ${var} = "-mode=RELEASE" ]; then
		CMD="${CMD} RELEASE=1"
	elif [ ${var} = "-mode=DEBUG" ]; then
		CMD="${CMD} DEBUG=1"
	elif [ ${var} = "-clean=1" ]; then
		echo $(make clean)
	fi
done

eval ${CMD}

