#!/bin/bash

cd build
./gen_workers.sh
cd ..

CMD="emmake make"

for var in "$@"
do
	if [ ${var} = "-mode=RELEASE" ]; then
		CMD="${CMD} RELEASE=1"
	elif [ ${var} = "-mode=DEBUG" ]; then
		CMD="${CMD} DEBUG=1"
	elif [ ${var} = "-mode=DEBUG_RELEASE" ]; then
		CMD="${CMD} DEBUG_RELEASE=1"
	elif [ ${var} = "-clean=1" ]; then
		echo $(make clean)
	fi
done

CMD="${CMD} EM_ASSERTIONS=1"

eval ${CMD}

