#!/bin/bash


if [ $1 = "nb" ]; then
	BROWSER=--no_browser
else
	BROWSER=--browser=$1
fi

emrun --verbose --serve_after_exit --serve_after_close ${BROWSER} bspviewer.html --log_stdout ./stdout.log --log_stderr ./stderr.log
